version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
